#!/bin/sh
# The control scaffold of the Patchwork workflow 'triage-report'.
#
# Generated by Patchwork's Graph Compiler. Edit the workflow, not this file.
#
# The umbrella beside it (SKILL.md) is read by a model, which is what makes its prose
# best-effort. This is read by a shell, which is what makes the two things it answers
# exact: the order the steps are followed in, and the branch a rule-based branch point
# takes for a given measured value. The model measures; this decides.
#
# Nothing here interprets what it is given: a measured value arrives as a positional
# argument and is compared as text or as an integer, never expanded and never run.
set -eu

usage='usage: control.sh plan | control.sh route <branch point> <measured value>'

die() {
  printf '%s\n' "control.sh: $1" >&2
  exit "$2"
}

# The order the umbrella's steps are followed in. Indented lines are the branches of
# the branch point above them, of which exactly one is taken.
plan() {
  printf '%s\n' \
    'step 1' \
    'branch point 1 (rule) — run: bash scripts/control.sh route 1 '\''<the value you measured>'\''' \
    '   branch point 1, branch `with trace`' \
    '     step 1 of branch point 1, branch `with trace`' \
    '   branch point 1, branch `no trace`' \
    '     step 1 of branch point 1, branch `no trace`' \
    'step 3' \
    'output'
}

# True when the value the model measured ($2) stands in the relation ($1) the author
# wrote to the value they wrote ($3).
#
# Both sides of an integer comparison are checked, and neither is trusted. `[ -gt ]`
# *fails* on a number outside the shell's integer range, and this function is asked
# inside an `if`, where a failure is indistinguishable from a false answer — so an
# unchecked value does not produce an error, it produces a branch, and which branch it
# produces differs between shells. Refusing exits the script instead.
holds() {
  case "$1" in
    equals) [ "$2" = "$3" ] ;;
    not-equals) [ "$2" != "$3" ] ;;
    contains) case "$2" in *"$3"*) return 0 ;; *) return 1 ;; esac ;;
    greater-than | less-than)
      comparable "$2" || die "'$2' is not a whole number of at most 9 digits, and this branch point compares numbers; measure it again as digits only, no larger than 999999999" 4
      comparable "$3" || die "this branch point compares against '$3', which no shell compares reliably; the rule it came from is out of range" 5
      if [ "$1" = "greater-than" ]; then
        [ "$2" -gt "$3" ]
      else
        [ "$2" -lt "$3" ]
      fi
      ;;
    *) die "unknown comparison '$1'" 5 ;;
  esac
}

# A whole number of at most 9 digits, which is what every shell
# compares the same way: POSIX guarantees `[` a signed long and no more, and the
# smallest one a conforming shell may have is 32 bits. Counted as text and never
# converted — a range check that did arithmetic would overflow the very type it is
# protecting.
comparable() {
  digits="${1#[+-]}"
  case "$digits" in
    '' | *[!0123456789]*) return 1 ;;
  esac
  # Leading zeros are padding, not magnitude.
  while :; do
    case "$digits" in
      0?*) digits="${digits#0}" ;;
      *) break ;;
    esac
  done
  [ "${#digits}" -le 9 ]
}

# The rule of each branch point the umbrella says this script decides, by the number
# the umbrella calls it. Anything else is refused rather than guessed at.
route() {
  case "$1" in
    1)
      operator='greater-than'
      operand='0'
      when_true='with trace'
      when_false='no trace'
      ;;
    *) die "this workflow has no rule-based branch point $1" 3 ;;
  esac
  if holds "$operator" "$2" "$operand"; then
    printf '%s\n' "$when_true"
  else
    printf '%s\n' "$when_false"
  fi
}

case "${1:-}" in
  plan)
    [ "$#" -eq 1 ] || die "$usage" 2
    plan
    ;;
  route)
    [ "$#" -eq 3 ] || die "$usage" 2
    route "$2" "$3"
    ;;
  *) die "$usage" 2 ;;
esac
