#!/bin/sh
# The control scaffold of the Patchwork workflow 'refine-draft'.
#
# Generated by Patchwork's Graph Compiler. Edit the workflow, not this file.
#
# The umbrella beside it (SKILL.md) is read by a model, which is what makes its prose
# best-effort. This is read by a shell, which is what makes the two things it answers
# exact: the order the steps are followed in, and how many passes a loop may run.
# The model does the work; this decides what must not vary.
#
# Nothing here interprets what it is given: a measured value arrives as a positional
# argument and is compared as text or as an integer, never expanded and never run.
#
# Where the workflow loops it answers one thing more, and records each pass to do it:
# how many passes a loop has run, and so whether it may run another. A shell remembers
# nothing between invocations, so every pass taken is recorded beside this script, and
# 'reset' removing those records is what starts a run of the workflow from zero.
set -eu

usage='usage: control.sh plan | control.sh loop <branch point> | control.sh reset'

die() {
  printf '%s\n' "control.sh: $1" >&2
  exit "$2"
}

# The order the umbrella's steps are followed in. Indented lines are the branches of
# the branch point above them, of which exactly one is taken.
plan() {
  printf '%s\n' \
    'step 1' \
    'branch point 1 (loop, at most 3) — run: bash scripts/control.sh loop 1' \
    '   branch point 1, branch `revise` — back to step 1' \
    '   branch point 1, branch `ship`' \
    'step 3' \
    'output'
}

# Where the passes already taken are recorded. One directory per pass of each loop,
# named by the branch point the umbrella calls that loop, so a human can count them and
# a run can be started over by deleting them.
state_dir="${PATCHWORK_LOOP_STATE:-$(dirname -- "$0")/.patchwork-loops}"

# Take a pass, if it is still there to be taken. Making a directory is the claim: it is
# atomic and it fails when the name is taken — by anything at all — so of any number of
# invocations racing for the same pass exactly one gets it. A redirection under `set -C`
# was not enough: noclobber refuses to overwrite a *regular* file and nothing else, so a
# device left at a pass's name was written and the pass taken again on every invocation,
# and a FIFO was opened and waited on for a reader that never came. `mkdir` refuses both
# and opens nothing. Quiet, because a pass somebody else holds is an answer here rather
# than an error.
claim() {
  mkdir -- "$1" 2>/dev/null
}

# True when a claim failed because that pass is already taken: a directory, and not a
# symlink to one. Anything else wearing the name is not a pass this script recorded, and
# is refused rather than read as a pass spent or a pass free.
held() {
  [ -d "$1" ] && [ ! -L "$1" ]
}

# Start a run of this workflow from zero. Only the passes this script recorded are
# removed, by name — never the directory they are in, and never anything else in it.
# One removal per name rather than one for all of them at once: a run that took very
# many passes would otherwise be permanently un-resettable, the whole glob being an
# argument list too long to pass to a command.
reset() {
  if [ -d "$state_dir" ]; then
    for claimed in "$state_dir"/loop-*; do
      # A pattern that matched nothing stands for itself, and is not a pass. `-L` beside
      # `-e` because a broken symlink is a name that exists while `-e` says it does not,
      # and one left behind is a pass that can never be claimed again.
      if [ ! -e "$claimed" ] && [ ! -L "$claimed" ]; then continue; fi
      rm -rf -- "$claimed" || die "cannot clear the passes recorded in '$state_dir'" 6
    done
  fi
  printf '%s\n' 'the loop counts are back to zero'
}

# How many passes each loop may run, by the branch point number the umbrella calls it.
# The count is this script's: the reader says it has reached the gate, and this says
# whether another pass is allowed. Anything else is refused rather than guessed at.
loop() {
  case "$1" in
    1)
      most='3'
      leave='ship'
      ;;
    *) die "this workflow has no loop at branch point $1" 3 ;;
  esac

  # Checked before anything is counted: a command that is not the one the umbrella gives
  # is refused, and a refusal must not cost this loop a pass — the reader is told to run
  # it again exactly as written.
  [ "$#" -eq 1 ] || die "$usage" 2

  mkdir -p -- "$state_dir" || die "cannot count this loop's passes in '$state_dir'" 6
  # Which pass this is, decided by taking one rather than by reading a number back: the
  # first pass nobody holds yet is this invocation's, and it is held from the moment it
  # is taken, so no second invocation can be on the same pass however they interleave.
  pass=0
  taking=1
  while [ "$taking" -le "$most" ]; do
    claimed="$state_dir/loop-$1-pass-$taking"
    if claim "$claimed"; then
      pass="$taking"
      break
    fi
    # A claim fails because somebody holds that pass, or because this bundle cannot
    # record one here at all, or because something that is not a pass is wearing the
    # name — and only looking afterwards tells the three apart. Left unasked, a state
    # directory it may not write would read as 'every pass is spent': bounded, but
    # silently uncounted, which is the one thing this must never be.
    if held "$claimed"; then
      taking=$((taking + 1))
      continue
    fi
    [ -e "$claimed" ] || [ -L "$claimed" ] || die "cannot count this loop's passes in '$state_dir'" 6
    die "'$claimed' is not a pass this script recorded, so this loop's passes cannot be counted; start the count over with 'reset'" 6
  done

  # Saturating: with every pass taken there is nothing left to take, so a loop that has
  # been stopped stays stopped however many times it is asked.
  if [ "$pass" -eq 0 ] || [ "$pass" -ge "$most" ]; then
    printf '%s\n' "$leave"
    return 0
  fi
  # No label, exit 0: the budget is not spent, so this branch point is the reader's.
  printf '%s\n' "control.sh: pass $pass of at most $most, so another pass is allowed and this branch point is yours to decide" >&2
}

case "${1:-}" in
  plan)
    [ "$#" -eq 1 ] || die "$usage" 2
    plan
    ;;
  loop)
    [ "$#" -ge 2 ] && [ "$#" -le 3 ] || die "$usage" 2
    shift
    loop "$@"
    ;;
  reset)
    [ "$#" -eq 1 ] || die "$usage" 2
    reset
    ;;
  *) die "$usage" 2 ;;
esac
